name: Deploy Supabase Frontend

on:
  push:
    branches: [main]
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # Installez les dépendances si vous utilisez SCSS
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Install dependencies
        run: |
          npm install -g sass
          npm ci
      
      # Compilez le SCSS si nécessaire
      - name: Build SCSS
        run: sass sass/:css/ --style compressed
      
      # Déployez sur GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Ou le dossier de sortie
